
export enum COUPON_USAGE_TYPE {
  SINGLE = 1,
  MULTIPLE
}

export enum COUPON_EXPIRE_TYPE {
  DATE = 1,
  TIME = 2
}

export enum COUPON_DISCOUNT_TYPE {
  AMOUNT = 1,
  PERCENT = 2
}

export enum COUPON_ORIGIN {
  WEB = 1,
  FILE = 2
}

export enum COUPON_STATUS {
  ACCEPT = 1,
  READY = 2,
  DISABLED = 3,
}

export enum COUPON_CODE_ORIGIN {
  BULK = 1, CONVERSATION, OTHER
}

export enum COUPON_CODE_STATUS {
  PENDING = 0,
  AVAILABLE = 1,
  DISTRIBUTED,
  VIEWED,
  CLAIMED,
  BLOCKED
}

export const COUPON_CODE_STATUS_STRING = {
  [COUPON_CODE_STATUS.AVAILABLE]: "AVAILABLE",
  [COUPON_CODE_STATUS.DISTRIBUTED]: "DISTRIBUTED",
  [COUPON_CODE_STATUS.VIEWED]: "VIEWED",
  [COUPON_CODE_STATUS.CLAIMED]: "CLAIMED",
  [COUPON_CODE_STATUS.BLOCKED]: "BLOCKED"
}

export enum COUPON_CODE_ACTION {
  DISTRIBUTE = 1,
  VIEW,
  CLAIM
}

export enum COUPON_ITEM_TYPE {
  TEXT = 1,
  QRCODE,
  BARCODE_128,
  BARCODE_EAN_13
}

export enum COUPON_GENERATE_TYPE {
  AUTO = 1,
  FIX
}
