export enum WHATSAPP_TEMPLATE_COMPONENT_TYPE {
  HEADER = 'HEADER',
  BODY = 'BODY',
  FOOTER = 'FOOTER',
  BUTTONS = 'BUTTONS',
  CAROUSEL = 'CAROUSEL',
  LIMITED_TIME_OFFER = 'LIMITED_TIME_OFFER',
}

export enum WHATSAPP_TEMPLATE_FORMAT {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  LOCATION = 'LOCATION',
}

export enum WHATSAPP_TEMPLATE_BUTTON_TYPE {
  COPY_CODE = 'COPY_CODE',
  PHONE_NUMBER = 'PHONE_NUMBER',
  QUICK_REPLY = 'QUICK_REPLY',
  ONE_TAP = 'ONE_TAP',
  URL = 'URL',
  MPM = 'MPM',
  SPM = 'SPM',
  CATALOG = 'CATALOG',
  NONE = 'NONE',
}

export enum WHATSAPP_TEMPLATE_CATEGORY {
  UTILITY = 'UTILITY',
  MARKETING = 'MARKETING',
  AUTHENTICATION = 'AUTHENTICATION',
}

export enum WHATSAPP_TEMPLATE_SUB_CATEGORY {
  CUSTOM = 'CUSTOM',
  CATALOG = 'CATALOG',
  FLOWS = 'FLOWS',
  ONE_TIME_PASSCODE = 'ONE_TIME_PASSCODE',
  CAROUSEL = 'CAROUSEL',
  SPM = 'SPM',
}

export enum WHATSAPP_TEMPLATE_STATUS {}

export enum WHATSAPP_BUTTON_URL_TYPE {
  DYNAMIC = 'dynamic',
  STATIC = 'static',
}
