export enum WHATSAPP_TEMPLATE_COMPONENT_TYPE {
  HEADER = "HEADER",
  BODY = "BODY",
  FOOTER = "FOOTER",
  BUTTONS = "BUTTONS"
}

export enum WHATSAPP_TEMPLATE_FORMAT {
  TEXT = "TEXT",
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  DOCUMENT = "DOCUMENT",
  LOCATION = "LOCATION"
}

export enum WHATSAPP_TEMPLATE_BUTTON_TYPE {
  COPY_CODE = "COPY_CODE",
  PHONE_NUMBER = "PHONE_NUMBER",
  QUICK_REPLY = "QUICK_REPLY",
  URL = "URL",
  MPM = "MPM",
  SPM = "spm"
}
