export enum BillingCategory {
  BILLING_CATEGORY_UNSPECIFIED = 'BILLING_CATEGORY_UNSPECIFIED',
  CONVERSATIONAL_LEGACY = 'CONVERSATIONAL_LEGACY',
  CONVERSATIONAL = 'CONVERSATIONAL',
  SINGLE_MESSAGE = 'SINGLE_MESSAGE',
  BASIC_MESSAGE = 'BASIC_MESSAGE'
}

export enum AgentUseCase {
  AGENT_USE_CASE_UNSPECIFIED = 'AGENT_USE_CASE_UNSPECIFIED',
  TRANSACTIONAL = 'TRANSACTIONAL',
  PROMOTIONAL = 'PROMOTIONAL',
  OTP = 'OTP',
  MULTI_USE = 'MULTI_USE'
}

export enum HostingRegion {
  HOSTING_REGION_UNSPECIFIED = 'HOSTING_REGION_UNSPECIFIED',
  NORTH_AMERICA = 'NORTH_AMERICA',
  EUROPE = 'EUROPE',
  ASIA_PACIFIC = 'ASIA_PACIFIC'
}

export enum LaunchState {
  LAUNCH_STATE_UNSPECIFIED = 'LAUNCH_STATE_UNSPECIFIED',
  LAUNCH_STATE_UNLAUNCHED = 'LAUNCH_STATE_UNLAUNCHED',
  LAUNCH_STATE_PENDING = 'LAUNCH_STATE_PENDING',
  LAUNCH_STATE_LAUNCHED = 'LAUNCH_STATE_LAUNCHED',
  LAUNCH_STATE_REJECTED = 'LAUNCH_STATE_REJECTED',
  LAUNCH_STATE_SUSPENDED = 'LAUNCH_STATE_SUSPENDED',
  LAUNCH_STATE_PENDING_UNLAUNCH = 'LAUNCH_STATE_PENDING_UNLAUNCH',
  LAUNCH_STATE_INVALID_IN_GMB = 'LAUNCH_STATE_INVALID_IN_GMB'
}

export enum VerificationState {
  VERIFICATION_STATE_UNSPECIFIED = 'VERIFICATION_STATE_UNSPECIFIED',
  VERIFICATION_STATE_UNVERIFIED = 'VERIFICATION_STATE_UNVERIFIED',
  VERIFICATION_STATE_PENDING = 'VERIFICATION_STATE_PENDING',
  VERIFICATION_STATE_VERIFIED = 'VERIFICATION_STATE_VERIFIED',
  VERIFICATION_STATE_SUSPENDED_IN_GMB = 'VERIFICATION_STATE_SUSPENDED_IN_GMB'
}

export enum IntegrationStatus{
  INTEGRATION_STATUS_UNSPECIFIED = 'INTEGRATION_STATUS_UNSPECIFIED',
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED'
}
