import {BACKGROUND_TASK} from "@peacom/model";
import {BACKGROUND_QUEUE} from "../../model";

export const getBackgroundTaskQueueName = (backgroundType: BACKGROUND_TASK) => {
  let rs = BACKGROUND_QUEUE.BACKGROUND_TASK;
  if (
    [
      BACKGROUND_TASK.GENERATE_CDR_FILE,
      BACKGROUND_TASK.IMPORT_BULK_CAMPAIGN_MULTI_FILE,
      BACKGROUND_TASK.IMPORT_CHECK_PHONE_RCS_MULTI_FILE,
      BACKGROUND_TASK.IMPORT_BACK_LIST_MULTI_FILE,
      BACKGROUND_TASK.IMPORT_BACK_LIST_GLOBAL_MULTI_FILE,
      BACKGROUND_TASK.IMPORT_CONTACT_MULTI_FILE,
      BACKGROUND_TASK.IMPORT_BULK_CAMPAIGN_FROM_STORAGE,
      BACKGROUND_TASK.IMPORT_BULK_CAMPAIGN_FROM_RETARGETING,
      BACKGROUND_TASK.CARRIER_CDR
    ].includes(backgroundType)
  ) {
    rs = BACKGROUND_QUEUE.BACKGROUND_TASK_SANDBOX;
  } else if ([
    BACKGROUND_TASK.GENERATE_COUPON_CODE,
    BACKGROUND_TASK.EXPORT_COUPON_CODE,
    BACKGROUND_TASK.GENERATE_IMAGE_COUPON_CODE,
    BACKGROUND_TASK.IMPORT_BULK_CONTACT_FROM_SEGMENT,
    BACKGROUND_TASK.EXPORT_CUSTOMER_FROM_SEGMENT
  ].includes(backgroundType)) {
    rs = BACKGROUND_QUEUE.BACKGROUND_CRM
  } else if (
    [
      BACKGROUND_TASK.BULK_CAMPAIGN_REPORT,
      BACKGROUND_TASK.EXPORT_CHAT_LOGS
    ].includes(backgroundType)
  ) {
    rs = BACKGROUND_QUEUE.BACKGROUND_BE;
  }
  return rs;
};
