export enum PEACOM_CORE_QUEUE {
  BILLING = 'MMP_CORE_BILLING',
  STATUS = 'MMP_CORE_MESSAGE_STATUS',
  STATUS_CONVERSATION = 'STATUS_CONVERSATION',
  STATUS_PRIORITY = 'MMP_CORE_MESSAGE_STATUS_PRIORITY',
  STATUS_TIME = 'STATUS_TIME',
  FALLBACK = 'MMP_CORE_FALLBACK',
  PARTNER = 'MMP_CORE_PARTNER',
  BULK_CAMPAIGN_BROADCAST = 'BULK_CAMPAIGN_BROADCAST',
  BACKGROUND_TASK = 'BACKGROUND_TASK',
  NOTIFICATION = 'MMP_NOTIFICATION',
  WEBHOOK = 'WEBHOOK',
  URL_CLICK_QUEUE = 'URL_CLICK_QUEUE',
  URL_CLICK_SUMMARY_QUEUE = 'URL_CLICK_SUMMARY_QUEUE',
}

export enum BACKGROUND_QUEUE {
  BACKGROUND_TASK = 'BACKGROUND_TASK',
  BACKGROUND_TASK_SANDBOX = 'BACKGROUND_TASK_SANDBOX',
  BACKGROUND_BE = 'BACKGROUND_BE',
  BACKGROUND_CRM = 'BACKGROUND_CRM'
}
