export enum PEACOM_CORE_QUEUE {
  BILLING = 'PEACOM_CORE_BILLING',
  STATUS = 'PEACOM_CORE_MESSAGE_STATUS',
  STATUS_PRIORITY = 'PEACOM_CORE_MESSAGE_STATUS_PRIORITY',
  FALLBACK = 'PEACOM_CORE_FALLBACK',
  PARTNER = 'PEACOM_CORE_PARTNER',
  BULK_CAMPAIGN_BROADCAST = 'BULK_CAMPAIGN_BROADCAST',
  BACKGROUND_TASK = 'BACKGROUND_TASK',
  NOTIFICATION = 'PEACOM_NOTIFICATION',
}
