export enum BACKGROUND_COUNTER {
  BULK_UPDATE_STATUS_READ = 1,
  BULK_UPDATE_STATUS_DELIVERED = 2,
  BULK_UPDATE_STATUS_FAIL = 3,
  BULK_UPDATE_STATUS_SENT = 4,
  BULK_FALLBACK_UPDATE_STATUS_READ = 5,
  BULK_FALLBACK_UPDATE_STATUS_DELIVERED = 6,
  BULK_FALLBACK_UPDATE_STATUS_FAIL = 7,
  BULK_FALLBACK_UPDATE_STATUS_SENT = 8,
  TICKET_INDEX
}
