/**
 * This is store on DB with tinyint (1byte), so the value must below 255
 * 01000010 => 66
 * 01000011 => 67
 */
export enum BILLING_STATUS {
  NONE = 0,
  PENDING = 1,
  BILLED = 2,
  CANCEL = 3,
  BILLED_CONFIRM = 66, /* Confirm escrow for success */
  CANCEL_CONFIRM = 67 /* Confirm escrow for cancel */
}

export enum COMPANY_BILLING_TYPE {
  POSTPAID = 1,
  PREPAID = 2
}

export enum TARIFF_TYPE {
  PER_BROADCAST_MESSAGE = 1,
  PER_CONVERSATION_MESSAGE,
  PER_CONVERSATION,
  PER_CONVERSATION_BROADCAST_INITIAL,
  PER_BROADCAST_MARKETING,
  PER_BROADCAST_UTILITY,
  PER_BROADCAST_AUTHENTICATION
}

export const tariffTypeStr = (tariffType: TARIFF_TYPE) => {
  switch (tariffType){
    case TARIFF_TYPE.PER_BROADCAST_MESSAGE:
      return 'BROADCAST MESSAGE'
    case TARIFF_TYPE.PER_BROADCAST_MARKETING:
      return 'BROADCAST MARKETING MESSAGE'
    case TARIFF_TYPE.PER_BROADCAST_UTILITY:
      return 'BROADCAST UTILITY MESSAGE'
    case TARIFF_TYPE.PER_BROADCAST_AUTHENTICATION:
      return 'BROADCAST AUTHENTICATION MESSAGE';
    case TARIFF_TYPE.PER_CONVERSATION_MESSAGE:
      return 'CONVERSATION MESSAGE'
    case TARIFF_TYPE.PER_CONVERSATION:
      return 'CONVERSATION'
    case TARIFF_TYPE.PER_CONVERSATION_BROADCAST_INITIAL:
      return 'CONVERSATION INITIAL BY BROADCAST'
    default:
      return `UNKNOWN ${tariffType}`
  }
}


export enum SETTING_TIME_TARIFF {
  HOUR = 1,
  DAY = 2,
  MONTH = 3
}
