export enum STORAGE_PARTNER {
  LOCAL = 1,
  AWS = 2
}

export enum STORAGE_TYPE {
  FILE = 1,
  FOLDER = 2
}

export enum STORAGE_SYSTEM_TYPE {
  USER_MANAGE = 1,
  SYSTEM_MANAGE = 2
}

export enum STORAGE_ORIGINAL {
  OTHER = 1,
  IMPORT_BULK_CAMPAIGN_INPUT = 2,
  IMPORT_CHECK_PHONE_RCS_INPUT = 3,
  IMPORT_CHECK_PHONE_RCS_RESULT = 4,
}
