export enum ORDER_STATUS {
  PENDING, CANCEL, CONFIRM, PROCESSING, FAIL, PARTIAL_DONE, DONE
}

export enum ORDER_PARTNER_STATUS {
  PENDING = 1,
  CONFIRM = 2,
  FAIL = 3,
  PROCESSING =4
}

export enum ORDER_CREATED_FROM_TYPE {
  PLATFORM = 1 ,
  API = 2,
  LANDING_PAGE
}
